version: "3.4"

services:
  postgres:
    image: postgres:12.7-alpine
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres